### ISSUE TITLE
Possible bug handling FAINT vs VFAINT

### ISSUE THREAD

**Issue by abmantz** [hiromasasuzuki/mkacispback#1]
It looks like the template models for FAINT mode are used in constructing the model even when the mode is VFAINT - is this a bug?

https://github.com/hiromasasuzuki/mkacispback/blob/b2da7940c2f95eea7b3350aa8710969c8bd95fbc/makemodelfunction_vfaint.sh#L128

**Comment by hiromasasuzuki** [comment]
Yes you seems right. I have fixed the

**Comment by hiromasasuzuki** [comment]
Yes you seems right. I have fixed the bug. Thanks!!
